### PR TITLE
feat: support Drupal 11

### PR DESCRIPTION
**Pull request by millnut**
## What does this change?

This module does not have any dependencies so we can bump the version to support Drupal 11

### CODE REVIEW

**Comment by ekes** [comment]
But shouldn't we start testing against D11 at the same time (or does this have to go in first to be able to run the tests?) Either way there should then be a MR to add D11 tests if we state that it is compatible?

**Comment by millnut** [comment]
> But shouldn't we start testing against D11 at the same time (or does this have to go in first to be able to run the tests?) Either way there should then be a MR to add D11 tests if we state that it is compatible?

We can't test D11 from the workflow as it will fail due to contrib dependencies not supporting D11 yet in the modules as well as the project. Due to this it will fail at the first stage of installing, I have the dependencies mapped out for D11 just need to upload the spreadsheet so we can start discussions around this.

**Comment by ekes** [comment]
So should we merge these ones, without dependencies, already without testing? Do we know if they are otherwise compatible?

**Comment by ekes** [comment]
MT consensus: We should make a plan of action and work out which of these to merge in which order. Meta issue for tracking this on the way ;-)

**Comment by markconroy** [comment]
I'm in favour for merging this one. Currently given our restraint is `>=10` we are in effect already supporting 11 (and anything that comes after it).

This PR says "we currently support 10 and 11 _only_"

**Review by ekes — APPROVED** [review]
There's a tracking meta. There's consensus on the issue. Adding to the merge queue by approving.

**Pull request merged**
